apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-cy-training
  name: nginx-cy-training
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-cy-training
  template:
    metadata:
      labels:
        app: nginx-cy-training
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: nginx
